feat: support OSCAL 1.1.2 (#1533)
* fix: hack component schema, moving metadata location to same as other
models

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: add large line-length specification to pyptroject.toml for
datamodel-codegen

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* doc: discourse on changes made.

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix - automate schema metadata relocation in comp-def

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: undo fwd refs

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: HowMany

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: update gen_oscal.md with info on automated schema relocations

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: isolate schema fixup code

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: preprocess improved move metadata & assign Type4

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix implementations move to common issues

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* OSCAL_VERSION 1.1.2

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* dynamic year for copyright

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: reorder by name pre-processing; some post-processing (hacking)

397 failed, 738 passed, 3 skipped, 34 warnings, 68 errors

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: code format/lint

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* hack: reduce failed/errors

386 failed, 785 passed, 3 skipped, 34 warnings, 32 errors

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: hack for EmailAddressDatatype

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: issue hack warning/info

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: handle special case of "id: TokenDatatype" in catalog

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: introduce schema patching and employ for email-address and
parameter-selection

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: handle RiskStatus properly when applying renaming

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* code format & lint

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: validation error for Base64

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix AttributeError: module 'trestle.oscal.ssp' has no attribute 'Status'

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix AttributeError: 'StringDatatype' object has no attribute 'strip'

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix Origin vs. Origin1

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* Add Observation to assessment_results from common

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix value is not a valid enumeration member

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: import__test.py::test_import_wrong_oscal_version

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* patch schemas to rename “status” to “objectiveStatus” to avoid conflict

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* patch POAM schema to make RelatedObservation same as the other models

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix base 64 issue

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: determine common TaskValidValues, ThreatIdValidValues

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: improve pre-process reordering; handle special cases & valid values

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: nist content ssp example has moved and changed

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: OSCAL version in data/tasks/xlsx/output/profile.json

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix tests/trestle/tasks/oscal_catalog_to_csv_test.py::test_execute

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: code generation of URIReferenceDatatype

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix test_xlsx_execute_with_missing_rule_name_id

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix tests/trestle/tasks/xlsx_to_oscal_profile_test.py

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix tests/trestle/tasks/csv_to_oscal_cd_test.py

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix tests/trestle/tasks/ocp4_cis_profile_to_oscal_cd_test.py

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: test_generate_sample_model - OscalVersion

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix TypeError: unhashable type: 'WithId'

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: logger.warn deprecation

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix :test_profile_alter_props - 'str' object has no attribute 'value'

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: AssertionError: assert StringDatatype(__root__='1.1.2') == '1.1.2'

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix lint error

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: get rid of python 3.7 use (hopefully)

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: sonar exclude generated code (hopefully)

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix direct hack of NIST schema for EmailAddress (handle in “normalizer”)

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix direct hack of NIST schema for Selection (HowMany)

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: add common valid values integrity check

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* rectification of property name changes (objective_status, originations)

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* TelephoneType and AddressType valid values

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* ExternalScheme and DocumentScheme valid values

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* DefinedComponentType valid values

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* SystemComponentType valid values

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* code comments

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* simplify pre-process code

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* simplify

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* remove unused code

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* replace deprecated pkg_resources with importlib_resources

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* Add python 3.10 to matrix

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* python 3.9, 3.10, 3.11

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* flake8 fix?

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* rename trestle.core.commands.author.profile to prof - lint shadow issue

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* update docs for change from author profile -> prof

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* add comments explaining refs creation in schema preprocessing

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* switch to pydantic latest version, but force v1 interface use for now

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: remedy 17 test warning by removing semantic release install

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* make sonar happy

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* make sonar happy

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* make sonar happy

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* use trestle.oscal.common.HowMany.one

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* supported versions of python are 3.9, 3.10. 3.11

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* reduce some duplication, as per reviewer's comments.

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: remove unused parameters, per reviewer comments.

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* revise imports per reviewer suggestion.

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* 2.7.0

Automatically generated by python-semantic-release

* restore python-semantic-release==7.33.2 to cfg (at old level, for now)

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* Remove "We've moved" from README

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: handle allOf construct (#1546)

* fix: handle allOf construct

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* How did .value get removed in 2 places??

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: merge & modify

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* test use of PositionValidValues as both string and enum

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* make flake8 happy

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* fix: unify create_refs + body integrity check

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

* remove use of extraneous constants

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

---------

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>

---------

Signed-off-by: Lou DeGenaro <lou.degenaro@gmail.com>
Co-authored-by: semantic-release <semantic-release>